version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"  # React
      - "5000:5000"  # Backend
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - /app/frontend/node_modules
      - /app/backend/node_modules
